using FTCERP.Host.Domain.Entities;

namespace FTCERP.Host.API.Responses;

public sealed record C88ConfigurationResponse(Guid PublicId, Guid MunicipalityFinancialYearPublicId, string FinancialYearCode, Guid CatalogueVersionPublicId, string CatalogueVersionCode, bool IsEnabled, DateTime EffectiveFrom, DateTime? EffectiveTo, string RowVersion);
public sealed record C88CatalogueVersionResponse(Guid PublicId, string Code, string Name, DateTime EditionDate, DateTime EffectiveFrom, DateTime? EffectiveTo, bool IsPublished, bool IsActive, string RowVersion);
public sealed record C88CatalogueItemResponse(Guid PublicId, Guid CatalogueVersionPublicId, C88CatalogueItemKind Kind, string Code, string Name, string? Description, Guid? ParentItemPublicId, int DisplayOrder, bool IsActive, string RowVersion);
public sealed record C88DataElementResponse(Guid PublicId, string Code, string Name, string? Description, C88ValueType ValueType, bool IsRequired, int Sequence, string RowVersion);
public sealed record C88ApplicabilityResponse(Guid PublicId, Guid MunicipalCategoryPublicId, Guid? ReadinessTierPublicId, bool IsApplicable, string? Notes);
public sealed record C88IndicatorResponse(Guid PublicId, Guid CatalogueVersionPublicId, string Code, string Name, string Definition, string OfficialTechnicalIndicatorDescription, Guid? SectorPublicId, Guid? OutcomePublicId, Guid? IndicatorTypePublicId, C88ValueType ValueType, C88ControlledCalculationOperator CalculationOperator, string? OfficialFormulaText, bool RequiresBaseline, bool RequiresMediumTermTarget, bool RequiresAnnualTarget, bool IsActive, string RowVersion, C88DataElementResponse[] DataElements, C88ApplicabilityResponse[] Applicability);
public sealed record C88ComplianceQuestionResponse(Guid PublicId, Guid CatalogueVersionPublicId, Guid ReportTypePublicId, Guid ResponseTypePublicId, string Code, string Prompt, bool IsRequired, int Sequence, bool IsActive, string RowVersion);
public sealed record C88IndicatorPlanResponse(Guid PublicId, Guid ConfigurationPublicId, Guid IndicatorPublicId, string IndicatorCode, string? BaselineValue, string? MediumTermTarget, string? AnnualTarget, string? MissingDataExplanation, DateTime? EstimatedAvailability, string RowVersion);
public sealed record C88ReportingCalendarResponse(Guid PublicId, Guid ConfigurationPublicId, Guid ReportTypePublicId, Guid? ReportingPeriodPublicId, string Code, string Name, DateTime OpensAt, DateTime ClosesAt, DateTime DueAt, bool IsActive, string RowVersion);
public sealed record C88DataElementValueResponse(Guid PublicId, Guid DataElementPublicId, string? Value, string? MissingDataExplanation, DateTime? EstimatedAvailability);
public sealed record C88ComplianceResponseResponse(Guid PublicId, Guid QuestionPublicId, string? Response, string? Comment);
public sealed record C88WorkflowActionResponse(Guid PublicId, int FromStageSequence, int ToStageSequence, C88WorkflowActionKind Action, string Reason, DateTime OccurredAt);
public sealed record C88IndicatorReportResponse(Guid PublicId, Guid ReportFamilyId, int VersionNumber, bool IsCurrent, Guid ConfigurationPublicId, Guid CalendarPublicId, Guid IndicatorPublicId, string IndicatorCode, C88ReportState State, int CurrentStageSequence, string? CalculatedValue, string? MissingDataExplanation, DateTime? EstimatedAvailability, DateTime CreatedAt, DateTime? FinalSubmittedAt, string RowVersion, C88DataElementValueResponse[] DataElementValues, C88ComplianceResponseResponse[] ComplianceResponses, C88WorkflowActionResponse[] WorkflowActions);
public sealed record C88AssignmentResponse(Guid PublicId, Guid ConfigurationPublicId, Guid IndicatorPublicId, Guid EmployeePublicId, string EmployeeName, C88AssignmentRole Role, DateTime EffectiveFrom, DateTime? EffectiveTo, bool IsActive, string RowVersion);
public sealed record C88WorkflowStageResponse(Guid PublicId, int Sequence, C88WorkflowStageKind Kind, string Name, C88AssignmentRole RequiredRole, bool IsActive);
public sealed record C88WorkflowResponse(Guid PublicId, Guid ConfigurationPublicId, int VersionNumber, bool IsCurrent, bool IsActive, DateTime EffectiveFrom, DateTime? EffectiveTo, string RowVersion, C88WorkflowStageResponse[] Stages);
public sealed record C88MappingResponse(Guid PublicId, Guid ConfigurationPublicId, Guid IndicatorPublicId, Guid OpmsTargetPublicId, string OpmsIndicatorNumber, C88MappingType MappingType, string Reason, bool IsActive, string RowVersion);
public sealed record C88WorkspaceResponse(C88CatalogueItemResponse[] CatalogueItems, C88IndicatorReportResponse[] Reports);
