namespace FTCERP.Host.API.Responses;

public sealed record StrategicDocumentTypeResponse(
    Guid PublicId,
    string Code,
    string Name,
    string? Description,
    bool AllowsExternalLinks,
    bool IsActive,
    int DisplayOrder,
    string RowVersion);

public sealed record StrategicDocumentEventResponse(
    Guid PublicId,
    string Action,
    string? Reason,
    Guid? ActorUserPublicId,
    string? ActorName,
    DateTime OccurredAt);

public sealed record StrategicDocumentResponse(
    Guid PublicId,
    Guid DocumentFamilyId,
    Guid? PreviousVersionPublicId,
    int VersionNumber,
    Guid MunicipalityFinancialYearPublicId,
    string FinancialYearCode,
    string FinancialYearName,
    Guid DocumentTypePublicId,
    string DocumentTypeCode,
    string DocumentTypeName,
    string? SdbipLayer,
    string Title,
    string? Description,
    DateTime DocumentDate,
    int DisplayOrder,
    bool IsCurrent,
    bool IsActive,
    bool IsApproved,
    DateTime? ApprovedAt,
    Guid? ApprovedByUserPublicId,
    string? ApprovedByName,
    string? ApprovalReference,
    bool IsPublished,
    DateTime? PublicationDate,
    DateTime? PublishedAt,
    Guid? PublishedByUserPublicId,
    string? PublishedByName,
    DateTime CreatedAt,
    Guid? CreatedByUserPublicId,
    string? CreatedByName,
    string? FileName,
    string? ContentType,
    long? SizeInBytes,
    string? Sha256,
    string? ScanStatus,
    string? ScannerProvider,
    string? ScannerReference,
    string? ScanDetail,
    bool IsQuarantined,
    string? ExternalUrl,
    string? ContentUrl,
    string RowVersion,
    StrategicDocumentEventResponse[] Events);
