// <auto-generated />
using System;
using FTCERP.Host.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FTCERP.Host.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618190322_AddLookupTablesAndSeedData")]
    partial class AddLookupTablesAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UnitId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.AuditFinding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Finding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("AuditFindings");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.BudgetSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BudgetSources");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.BudgetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BudgetTypes");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.DueDateExtension", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExtendedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OriginalDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.ToTable("DueDateExtensions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsSubmission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Actual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ActualDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ActualExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApproverUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("AuditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditorComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorrectiveMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExtendedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpmsTargetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PmsComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PmsOfficerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PmsReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("SubmitterScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Variance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VarianceReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifierComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifierUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("AuditorUserId");

                    b.HasIndex("IpmsTargetId");

                    b.HasIndex("PmsOfficerUserId");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("VerifierUserId");

                    b.ToTable("IpmsSubmissions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsTarget", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AnnualTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AnnualTargetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Baseline")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BudgetSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("BudgetTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FunctionalArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdpReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevised")
                        .HasColumnType("bit");

                    b.Property<string>("KpiDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KpiType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MidTermTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MunicipalKpa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalKpa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceObjective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Q1Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q1Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q1Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q2Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q2Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MidTermTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MidTermDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MidTermBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q3Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q3Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3RevisedTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q4Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q4Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4RevisedTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevisedAnnualTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevisedAnnualBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RelatedOpmsTargetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceTemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceTemplateVersion")
                        .HasColumnType("int");

                    b.Property<int?>("StrategicGoalId")
                        .HasColumnType("int");

                    b.Property<int?>("StrategicObjectiveId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("BudgetSourceId");

                    b.HasIndex("BudgetTypeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("RelatedOpmsTargetId");

                    b.HasIndex("StrategicGoalId");

                    b.HasIndex("StrategicObjectiveId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("IpmsTargets");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsTargetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AnnualTargetDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultPoeRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultRatingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultScoreScale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTaskTemplatesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionalArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("JobGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KpiDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LinkedOpmsTargetRequired")
                        .HasColumnType("bit");

                    b.Property<string>("PerformanceArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCode")
                        .IsUnique();

                    b.ToTable("IpmsTargetTemplates");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsTargetTemplateVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IpmsTargetTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IpmsTargetTemplateId");

                    b.ToTable("IpmsTargetTemplateVersions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.LoginAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginAuditLogs");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsSubmission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Actual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ActualDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ActualExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApproverUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("AuditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditorComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorrectiveMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExtendedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpmsTargetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PmsComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PmsOfficerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PmsReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("SubmitterScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Variance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VarianceReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifierComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifierUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("AuditorUserId");

                    b.HasIndex("OpmsTargetId");

                    b.HasIndex("PmsOfficerUserId");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("VerifierUserId");

                    b.ToTable("OpmsSubmissions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsTarget", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdditionalAssigneeIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AnnualTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AnnualTargetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Baseline")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BaselineDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BudgetSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("BudgetTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FmsLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionalArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdpReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevised")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWithdrawn")
                        .HasColumnType("bit");

                    b.Property<string>("KpiDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KpiType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MidTermBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MidTermDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MidTermTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MunicipalKpa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalKpa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceObjective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Q1Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q1Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q1Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q2Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q2Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q2Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q3Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q3RevisedTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q3Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Q4Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Q4RevisedTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Q4Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReasonForWithdrawal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RevisedAnnualBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevisedAnnualTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceTemplateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceTemplateVersion")
                        .HasColumnType("int");

                    b.Property<string>("StandardClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StrategicGoalId")
                        .HasColumnType("int");

                    b.Property<int?>("StrategicObjectiveId")
                        .HasColumnType("int");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<string>("VoteNumberIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WardIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("BudgetSourceId");

                    b.HasIndex("BudgetTypeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("StrategicGoalId");

                    b.HasIndex("StrategicObjectiveId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("OpmsTargets");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsTargetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AnnualTargetDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Baseline")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BudgetSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudgetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultBudgetInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultPoeRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultQuarterlyTargetsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FmsLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionalArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdpReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicatorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("KpiDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KpiType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipalKpa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalKpa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityIssue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardClassification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrategicGoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrategicObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCode")
                        .IsUnique();

                    b.ToTable("OpmsTargetTemplates");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsTargetTemplateVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpmsTargetTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpmsTargetTemplateId");

                    b.ToTable("OpmsTargetTemplateVersions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.PoeFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpmsSubmissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OpmsSubmissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionKind")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IpmsSubmissionId");

                    b.HasIndex("OpmsSubmissionId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("PoeFiles");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.ReviewComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IpmsSubmissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OpmsSubmissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentedByUserId");

                    b.HasIndex("IpmsSubmissionId");

                    b.HasIndex("OpmsSubmissionId");

                    b.ToTable("ReviewComments");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.StrategicGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StrategicGoals");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.StrategicObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StrategicGoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("StrategicGoalId");

                    b.ToTable("StrategicObjectives");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.SubmissionScore", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IpmsSubmissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpmsSubmissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScoredByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IpmsSubmissionId");

                    b.HasIndex("OpmsSubmissionId");

                    b.HasIndex("ScoredByUserId");

                    b.ToTable("SubmissionScores");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Code")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitOfMeasures");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.UserAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KpiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssignments");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.UserPermissionOverride", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissionOverrides");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.UserScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("KpiId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScopeType")
                        .HasColumnType("int");

                    b.Property<string>("TargetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UserId");

                    b.ToTable("UserScopes");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.VoteNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("VoteNumbers");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.Department", "DepartmentEntity")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.Unit", "UnitEntity")
                        .WithMany("Users")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DepartmentEntity");

                    b.Navigation("UnitEntity");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.AuditFinding", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.AuditTrail", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.DueDateExtension", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsSubmission", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId");

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "AuditorUser")
                        .WithMany()
                        .HasForeignKey("AuditorUserId");

                    b.HasOne("FTCERP.Host.Domain.Entities.IpmsTarget", "IpmsTarget")
                        .WithMany("Submissions")
                        .HasForeignKey("IpmsTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "PmsOfficerUser")
                        .WithMany()
                        .HasForeignKey("PmsOfficerUserId");

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "VerifierUser")
                        .WithMany()
                        .HasForeignKey("VerifierUserId");

                    b.Navigation("ApproverUser");

                    b.Navigation("AuditorUser");

                    b.Navigation("IpmsTarget");

                    b.Navigation("PmsOfficerUser");

                    b.Navigation("SubmittedByUser");

                    b.Navigation("VerifierUser");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsTarget", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.BudgetSource", "BudgetSource")
                        .WithMany()
                        .HasForeignKey("BudgetSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.BudgetType", "BudgetType")
                        .WithMany()
                        .HasForeignKey("BudgetTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.OpmsTarget", "RelatedOpmsTarget")
                        .WithMany()
                        .HasForeignKey("RelatedOpmsTargetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.StrategicGoal", "StrategicGoal")
                        .WithMany()
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.StrategicObjective", "StrategicObjective")
                        .WithMany()
                        .HasForeignKey("StrategicObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUser");

                    b.Navigation("BudgetSource");

                    b.Navigation("BudgetType");

                    b.Navigation("Department");

                    b.Navigation("Period");

                    b.Navigation("RelatedOpmsTarget");

                    b.Navigation("StrategicGoal");

                    b.Navigation("StrategicObjective");

                    b.Navigation("Unit");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsTargetTemplateVersion", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.IpmsTargetTemplate", "IpmsTargetTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("IpmsTargetTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IpmsTargetTemplate");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.LoginAuditLog", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "User")
                        .WithMany("LoginAuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsSubmission", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId");

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "AuditorUser")
                        .WithMany()
                        .HasForeignKey("AuditorUserId");

                    b.HasOne("FTCERP.Host.Domain.Entities.OpmsTarget", "OpmsTarget")
                        .WithMany("Submissions")
                        .HasForeignKey("OpmsTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "PmsOfficerUser")
                        .WithMany()
                        .HasForeignKey("PmsOfficerUserId");

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "VerifierUser")
                        .WithMany()
                        .HasForeignKey("VerifierUserId");

                    b.Navigation("ApproverUser");

                    b.Navigation("AuditorUser");

                    b.Navigation("OpmsTarget");

                    b.Navigation("PmsOfficerUser");

                    b.Navigation("SubmittedByUser");

                    b.Navigation("VerifierUser");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsTarget", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.BudgetSource", "BudgetSource")
                        .WithMany()
                        .HasForeignKey("BudgetSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.BudgetType", "BudgetType")
                        .WithMany()
                        .HasForeignKey("BudgetTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.StrategicGoal", "StrategicGoal")
                        .WithMany()
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.StrategicObjective", "StrategicObjective")
                        .WithMany()
                        .HasForeignKey("StrategicObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUser");

                    b.Navigation("BudgetSource");

                    b.Navigation("BudgetType");

                    b.Navigation("Department");

                    b.Navigation("Period");

                    b.Navigation("StrategicGoal");

                    b.Navigation("StrategicObjective");

                    b.Navigation("Unit");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsTargetTemplateVersion", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.OpmsTargetTemplate", "OpmsTargetTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("OpmsTargetTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpmsTargetTemplate");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.PoeFile", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.IpmsSubmission", null)
                        .WithMany("PoeFiles")
                        .HasForeignKey("IpmsSubmissionId");

                    b.HasOne("FTCERP.Host.Domain.Entities.OpmsSubmission", null)
                        .WithMany("PoeFiles")
                        .HasForeignKey("OpmsSubmissionId");

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.ReviewComment", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "CommentedByUser")
                        .WithMany()
                        .HasForeignKey("CommentedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FTCERP.Host.Domain.Entities.IpmsSubmission", null)
                        .WithMany("ReviewComments")
                        .HasForeignKey("IpmsSubmissionId");

                    b.HasOne("FTCERP.Host.Domain.Entities.OpmsSubmission", null)
                        .WithMany("ReviewComments")
                        .HasForeignKey("OpmsSubmissionId");

                    b.Navigation("CommentedByUser");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.StrategicObjective", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.StrategicGoal", "StrategicGoal")
                        .WithMany()
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategicGoal");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.SubmissionScore", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.IpmsSubmission", null)
                        .WithMany("Scores")
                        .HasForeignKey("IpmsSubmissionId");

                    b.HasOne("FTCERP.Host.Domain.Entities.OpmsSubmission", null)
                        .WithMany("Scores")
                        .HasForeignKey("OpmsSubmissionId");

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "ScoredByUser")
                        .WithMany()
                        .HasForeignKey("ScoredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScoredByUser");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Unit", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.Department", "Department")
                        .WithMany("Units")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.UserAssignment", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.UserPermissionOverride", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissionOverrides")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "User")
                        .WithMany("PermissionOverrides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.UserScope", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.Department", "Department")
                        .WithMany("UserScopes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.Unit", "Unit")
                        .WithMany("UserScopes")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Scopes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.VoteNumber", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FTCERP.Host.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("LoginAuditLogs");

                    b.Navigation("PermissionOverrides");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Department", b =>
                {
                    b.Navigation("Units");

                    b.Navigation("UserScopes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsSubmission", b =>
                {
                    b.Navigation("PoeFiles");

                    b.Navigation("ReviewComments");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsTarget", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.IpmsTargetTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsSubmission", b =>
                {
                    b.Navigation("PoeFiles");

                    b.Navigation("ReviewComments");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsTarget", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.OpmsTargetTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissionOverrides");
                });

            modelBuilder.Entity("FTCERP.Host.Domain.Entities.Unit", b =>
                {
                    b.Navigation("UserScopes");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
